# Generated by Django 4.0.1 on 2022-01-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRelease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
